language: scala
scala:
- 2.12.8
jdk:
- openjdk8
sudo: false
cache:
  yarn: true
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - website/node_modules
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle
stages:
  - name: test
  - name: microsite
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
  - name: publishMicrosite
    if: tag IS present
jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++$TRAVIS_SCALA_VERSION coverage startDynamodbLocal test dynamodbLocalTestCleanup stopDynamodbLocal
      after_success: bash <(curl -s https://codecov.io/bash)
    - &microsite
      stage: microsite
      name: "Generate microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION docs/docusaurusCreateSite
    - &release
      stage: release
      name: "Release artifacts"
      script: sbt ci-release
    - &publishSite
      stage: publishMicrosite
      script: sbt ++$TRAVIS_SCALA_VERSION docs/docusaurusPublishGhpages

    # Cross-build
    - <<: *test
      scala: 2.11.12
      name: "Test for 2.11"
